### ISSUE TITLE
Add herobrine

### ISSUE THREAD

**Issue by theimk** [SDFTDusername/cpp-examples#1]
oretty please

**Comment by SDFTDusername** [comment]
can you create a pull request because im physically able to write

**Comment by theimk** [comment]
thanks it worke dbut aaeaseads
```bash
rm -rf /
````

**Comment by SDFTDusername** [comment]
you are great person thanks
![Minion_micdrop_gmail](https://github.com/SDFTDusername/cpp-examples/assets/85052868/d57faee2-ebac-4fa5-9225-a560bf0c9b44)
